FROM python:3.11-slim

# предотвращаем .pyc и буферизацию логов
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# ---------------------------
# 1. Сначала только зависимости
# ---------------------------

COPY requirements.txt /app/requirements.txt

# используем cache mount для pip (ВАЖНО)
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip && \
    pip install -r requirements.txt

# ---------------------------
# 2. Потом код (чтобы не сбивать cache)
# ---------------------------

COPY . /app

# ---------------------------
# 3. запуск
# ---------------------------

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]