server:
  forward-headers-strategy: framework
  port: 8877

spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.77.10:8081/.well-known/jwks.json
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: site
            uri: http://192.168.77.10:5173
            predicates:
            - Path=/site/**
            filters:
            - StripPrefix=1
          - id: site-static
            uri: http://192.168.77.10:5173
            predicates:
            - Path=/static/**
          - id: site-vite
            uri: http://192.168.77.10:5173
            predicates:
            - Path=/@vite/**
          - id: site-src
            uri: http://192.168.77.10:5173
            predicates:
            - Path=/src/**
          - id: site-react-refresh
            uri: http://192.168.77.10:5173
            predicates:
            - Path=/@react-refresh/**
          - id: site-node-modules
            uri: http://192.168.77.10:5173
            predicates:
            - Path=/node_modules/**



          - id: profile
            uri: http://192.168.77.10:8080
            predicates:
            - Path=/profile/**
            filters:
            - StripPrefix=1
          - id: recommendations
            uri: http://192.168.77.10:8077
            predicates:
            - Path=/recommendations/**
            filters:
            - StripPrefix=1
          - id: recruitment
            uri: http://192.168.77.10:8078
            predicates:
            - Path=/recruitment/**
            filters:
            - StripPrefix=1
          - id: user
            uri: http://192.168.77.10:8081
            predicates:
            - Path=/user/**
            filters:
            - StripPrefix=1