spring:
  elasticsearch:
    uris: http://localhost:9200
  r2dbc:
    url: r2dbc:postgresql://192.168.77.10:5453/profile_db
    username: wave
    password: Den1234567890/
  flyway:
    url: jdbc:postgresql://192.168.77.10:5453/profile_db
    locations: classpath:db/migrations
    user: wave
    password: Den1234567890/
    enabled: true