spring:
  config:
    activate:
      on-profile: dev
  r2dbc:
    url:
    username:
    password:
  flyway:
    url:
    locations: classpath:db/migrations
    user:
    password:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8078